---
initialized: null
deck: 'deck.json'
question: 'prompts/question_prompt.txt'
answer: 'prompts/answer_prompt.txt'
model params: 
  connection: 'ollama'
  model_type: 'llama3.2:1b'
  host: 'http://localhost:11434'